# Generated by Django 6.1.1 on 2026-09-24 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('crop_name', models.CharField(db_index=True, max_length=80)),
                ('quantity', models.CharField(max_length=60)),
                ('quantity_quintals', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('crop_picture', models.TextField(blank=True)),
                ('crop_address', models.TextField()),
                ('base_price_per_quintal', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('current_highest_bid', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('bidding_start_time', models.DateTimeField(auto_now_add=True)),
                ('bidding_end_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('Bidding Active', 'Bidding Active'), ('Bidding Completed', 'Bidding Completed'), ('Bid Accepted', 'Bid Accepted'), ('Bid Rejected', 'Bid Rejected'), ('Purchased', 'Purchased'), ('Expired', 'Expired')], db_index=True, default='Bidding Active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_lots', to='authentication.userprofile')),
                ('winning_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_crop_lots', to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AllocatedLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_purchase_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_deadline', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('Pending Purchase', 'Pending Purchase'), ('Purchased', 'Purchased'), ('Expired', 'Expired')], db_index=True, default='Pending Purchase', max_length=30)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('utr_reference', models.CharField(blank=True, max_length=80)),
                ('payment_mode', models.CharField(blank=True, default='AgriTradeX Escrow RTGS Transfer', max_length=80)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_allocations', to='authentication.userprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_lots', to='authentication.userprofile')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='marketplace.croplot')),
            ],
        ),
        migrations.CreateModel(
            name='VendorBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('bid_amount_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_lot_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Outbid', 'Outbid'), ('Expired', 'Expired')], default='Active', max_length=30)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='marketplace.croplot')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_bids', to='authentication.userprofile')),
            ],
        ),
    ]
