# Generated by Django 6.1.1 on 2026-09-24 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBuyingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_distance_km', models.IntegerField(default=50)),
                ('selected_crops', models.JSONField(default=list)),
                ('min_quantity_quintals', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('max_quantity_quintals', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buying_preferences', to='authentication.userprofile')),
            ],
        ),
    ]
