# Generated by Django 6.1.1 on 2026-09-24 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('crop_name', models.CharField(max_length=80)),
                ('quantity', models.CharField(max_length=60)),
                ('crop_picture', models.TextField(blank=True)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('Payment Pending', 'Payment Pending'), ('Payment Completed', 'Payment Completed')], db_index=True, default='Payment Pending', max_length=30)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_time', models.CharField(blank=True, max_length=30)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('utr_reference', models.CharField(blank=True, max_length=80)),
                ('payment_mode', models.CharField(blank=True, default='Direct Bank NEFT / RTGS Transfer', max_length=80)),
                ('crop_purchase_receipt_picture', models.TextField(blank=True)),
                ('crop_receipt_file_name', models.CharField(blank=True, max_length=150)),
                ('crop_receipt_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('payment_receipt_picture', models.TextField(blank=True)),
                ('payment_receipt_file_name', models.CharField(blank=True, max_length=150)),
                ('payment_receipt_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_transactions', to='authentication.userprofile')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='marketplace.croplot')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_transactions', to='authentication.userprofile')),
            ],
        ),
    ]
