# Generated by Django 6.1.1 on 2026-09-24 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivatedCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(db_index=True, max_length=80)),
                ('category', models.CharField(blank=True, default='Commercial Crop', max_length=80)),
                ('variety', models.CharField(blank=True, default='Hybrid', max_length=100)),
                ('acres_allocated', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('estimated_yield_quintals', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('photo_url', models.TextField(blank=True)),
                ('crop_address', models.TextField(blank=True)),
                ('stage', models.CharField(default='Vegetative Growth', max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cultivating', 'Cultivating'), ('Harvested', 'Harvested')], default='Active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivated_crops', to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CropProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_title', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('photo_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='crops.cultivatedcrop')),
            ],
        ),
        migrations.CreateModel(
            name='MarketPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(db_index=True, max_length=80)),
                ('date', models.DateField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='₹ per Quintal', max_length=40)),
                ('trend', models.CharField(default='stable', max_length=20)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('crop_name', 'date')},
            },
        ),
    ]
