# Generated by Django 6.1.1 on 2026-09-24 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('role', models.CharField(default='farmer', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('vendor', 'Vendor')], db_index=True, max_length=20)),
                ('mobile_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('state', models.CharField(default='Telangana', max_length=80)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('mandal', models.CharField(blank=True, max_length=80)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('land_acres', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('land_survey_number', models.CharField(blank=True, max_length=60)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('company_id', models.CharField(blank=True, max_length=60)),
                ('gst_number', models.CharField(blank=True, max_length=30)),
                ('trade_license_number', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(default='State Bank of India', max_length=120)),
                ('branch_name', models.CharField(default='Agricultural Development Branch', max_length=120)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='authentication.userprofile')),
            ],
        ),
    ]
