# Generated by Django 6.1.1 on 2026-09-24 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('land_acres', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('land_survey_number', models.CharField(max_length=80)),
                ('crop_name', models.CharField(default='Cotton', max_length=80)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('eligible_amount', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('pattadar_passbook_doc', models.TextField(blank=True)),
                ('adangal_doc', models.TextField(blank=True)),
                ('soil_health_doc', models.TextField(blank=True)),
                ('documents_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('No Loan Application', 'No Loan Application'), ('Loan Application Submitted', 'Loan Application Submitted'), ('Under Vendor Review', 'Under Vendor Review'), ('Loan Accepted', 'Loan Accepted'), ('Loan Rejected', 'Loan Rejected'), ('Agreement Pending', 'Agreement Pending'), ('Agreement Accepted', 'Agreement Accepted'), ('Loan Amount Disbursed', 'Loan Amount Disbursed')], db_index=True, default='Loan Application Submitted', max_length=40)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='authentication.userprofile')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loans', to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LoanAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
                ('tenure_months', models.IntegerField(default=6)),
                ('terms_text', models.TextField(blank=True)),
                ('repayment_terms', models.TextField(blank=True)),
                ('vendor_accepted', models.BooleanField(default=True)),
                ('vendor_accepted_at', models.DateTimeField(auto_now_add=True)),
                ('farmer_accepted', models.BooleanField(default=False)),
                ('farmer_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Agreement Pending', 'Agreement Pending'), ('Agreement Accepted', 'Agreement Accepted'), ('Loan Amount Disbursed', 'Loan Amount Disbursed')], db_index=True, default='Agreement Pending', max_length=40)),
                ('disbursal_date', models.DateField(blank=True, null=True)),
                ('disbursal_utr', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_agreements', to='authentication.userprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_agreements', to='authentication.userprofile')),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='loans.loanapplication')),
            ],
        ),
    ]
