# Generated by Django 6.1.1 on 2026-09-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='verification_status',
            field=models.CharField(choices=[('Pending Verification', 'Pending Verification'), ('Documents Verified', 'Documents Verified'), ('Documents Not Verified', 'Documents Not Verified')], default='Pending Verification', max_length=40),
        ),
    ]
